### ISSUE TITLE
improvement in coupon copy button

### ISSUE THREAD

**Issue by anonymgit** [AliReza1083/AniLearn.dev#10]
# issue
- when client get clicked on coupon copy button it does not changing the state.

# solution and how it should look there
- when client get clicked on copy button it should copy the text to clipboard and icon should be change to checked,and copy button should be blocked after operation.

**Comment by anonymgit** [comment]
i can improve that.

**Comment by AliReza1083** [comment]
Hi,
That is a good idea.
This issue will be assigned to you.
Good luck

**Comment by AliReza1083** [comment]
Done ✅
