### ISSUE TITLE
[Typo] There is one typo in the filter page

### ISSUE THREAD

**Issue by shubhsharma19** [AliReza1083/AniLearn.dev#14]
## Description

As you can see there is one typo: 

Instead of "Add you own Image URL" it should be "Add your own Image URL"

## Screenshot

![brave_27jujJbXeA](https://github.com/AliReza1083/AniLearn.dev/assets/69891912/38a3f135-7798-45dd-944c-71ec879bf2f7)

**Comment by AliReza1083** [comment]
Fixed by @shubhsharma19
