### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [AliReza1083/AniLearn.dev#16]
## Description
I have noticed that the README.md appears to be incomplete. There is an error in step 2 of the Contributing section, where it states "Clone t" instead of "Clone the Repository". Additionally, step 3 instructs to navigate to the "4c-site" directory instead of "AniLearn.dev". I would like to propose adding additional steps for staging, committing, and creating a pull request. I am enthusiastic about contributing to this project and would appreciate your assignment. I have attached a screenshot for your reference.

## Screenshots

![Screenshot (12)](https://github.com/AliReza1083/AniLearn.dev/assets/112751524/e966510a-976d-4eee-946b-77cd67a62a63)

**Comment by AliReza1083** [comment]
Hi,
I didn't take the readme.md file seriously but we must a good file so that everyone can understand it.

This issue will be assigned to you.
Goos luck

**Comment by AliReza1083** [comment]
If you give a target date for this issue to be solved, that would be great.

**Comment by shubhsharma19** [comment]
Great I just saw this issue! Thanks for the mention

**Comment by Shiva-Sai-ssb** [comment]
> If you give a target date for this issue to be solved, that would be great.

Thank you for assigning. I assure you that I will definitely submit a pull request either today or tomorrow.

**Comment by AliReza1083** [comment]
> > If you give a target date for this issue to be solved, that would be great.
> 
> Thank you for assigning. I assure you that I will definitely submit a pull request either today or tomorrow.

That's great, Shiva!
