### ISSUE TITLE
[Docs]: Add pnpm install step

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [AliReza1083/AniLearn.dev#20]
### Description

I recommend including a step that guides contributors to confirm they have the pnpm package manager installed separately, as it will not be automatically downloaded when installing node.js.

### Anything else?

I believe it would be beneficial to include an additional step for installing pnpm at this location.
![Screenshot (20)](https://github.com/AliReza1083/AniLearn.dev/assets/112751524/5ae386d9-100a-4d6d-ab5d-c911b59e18a6)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
Yeah, you are right, we have to add it.
Are you willing to do it?

**Comment by Shiva-Sai-ssb** [comment]
> Yeah, you are right, we have to add it. Are you willing to do it?

Yeah, I am willing to work on it.
Kindly assign this issue to me.

**Comment by AliReza1083** [comment]
Would you be able to add these badges on the top of the Readme.md file?
Just the license, release & repo size.

![image](https://github.com/AliReza1083/AniLearn.dev/assets/99729607/4961a6d5-f168-4e22-a5fa-2b36001e3383)

You can see the file [here](https://github.com/EddieHubCommunity/LinkFree).

**Comment by Shiva-Sai-ssb** [comment]
> Would you be able to add these badges on the top of the Readme.md file? Just the license, release & repo size badge.
> 
> ![image](https://user-images.githubusercontent.com/99729607/246351465-4961a6d5-f168-4e22-a5fa-2b36001e3383.png)
> 
> You can see the file [here](https://github.com/EddieHubCommunity/LinkFree).

Yeah, I will add these too.

**Comment by Shiva-Sai-ssb** [comment]
> What do you think if we add this at the end as well? Will it look great?
> 
> ![image](https://user-images.githubusercontent.com/99729607/246352775-89962231-0759-4868-a943-c4580250afcd.png)

It will look good. Should I add them too?

**Comment by AliReza1083** [comment]
Yeah, it will great.

**Comment by Shiva-Sai-ssb** [comment]
> Yeah, it will great.

Since we don't have a Discord channel for this project, I think I should only add the license and star the repository points. Right?

**Comment by AliReza1083** [comment]
Yes, there is no need to add the discord link since we don't have it.

**Comment by Shiva-Sai-ssb** [comment]
> Yes, there is no need to add the discord link since we don't have it.

Okay, I will make the necessary changes and submit a pull request as soon as possible.

**Comment by AliReza1083** [comment]
Thank you for putting your time :)
