### ISSUE TITLE
[Bug]: Graphical submit button is broken

### ISSUE THREAD

**Issue by bulletinmybeard** [AliReza1083/AniLearn.dev#22]
### Description

It seems the `src` attribute for the graphical submit button is missing / broken.

### To Reproduce

1. Go to https://www.anilearn.dev/html/inputs
2. Scroll down to the `Image` example

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
Thanks for the issue,
Now it is fixed.
