### ISSUE TITLE
[Feat]: CSS Display-Property

### ISSUE THREAD

**Issue by bulletinmybeard** [AliReza1083/AniLearn.dev#23]
### Description

On [https://www.anilearn.dev/css/display-property](https://www.anilearn.dev/css/display-property), there is no visual change when switching between `inline` and `inline-block`.

### Solution

Since only the header inline style is being updated, there is no visual change between `inline` and `inline-block`. To change that, consider updating the paragraph element underneath the header as well or update the entire example.

<img width="919" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/4e21776e-d2f1-45be-ad2e-ab3c15548dde">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
Thanks for the issue,
Would you please check now and tell us how it is?

https://www.anilearn.dev/css/display-property

**Comment by AliReza1083** [comment]
If I use image instead of a paragraph, will that be okay?

**Comment by AliReza1083** [comment]
This issue has been fixed.
Thanks for the issue
