### ISSUE TITLE
[Bug]: User input image URLs need additional validation

### ISSUE THREAD

**Issue by bulletinmybeard** [AliReza1083/AniLearn.dev#24]
### Description

BTW. This applies to all input fields for custom image URLs.

## https://www.anilearn.dev/css/filter
Works with image URLs like `https://miro.medium.com/v2/format:webp/1*LFSrbkB_nFr65tCSa4vaaw.png`, but needs additional validation.

**Works**
<img width="792" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/e5b5b3e9-dbe2-479c-91cd-ee1f0b43270a">

**Does not work, obviously**
<img width="734" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/7f213781-e7be-487f-8ed4-828eecdba4fd">

## https://www.anilearn.dev/css/object-fit
Does not work with `https://miro.medium.com/v2/resize:fit:1400/format:webp/1*LFSrbkB_nFr65tCSa4vaaw.png` and any other valid image URLs and needs additional validation on top of it.

You could use something like the following to determine whether the given URL is an image and display an error message if no valid image was found:

```
const urlContainsImage = async (url) => {
  const response = await fetch(url, { method: 'GET' })
  if (response && response?.ok) {
      const contentType = response.headers.get('content-type')
      if (contentType) {
          return contentType.startsWith('image/')
      }
  }
  return false
}
```

### To Reproduce

Applies to all custom user input fields for image URLs.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
We can say:

if there is no image found, then we can display a default image. 
what do you think?

**Comment by bulletinmybeard** [comment]
That's exactly what I would do, top!!!

**Comment by AliReza1083** [comment]
This issue has been fixed.
Thanks for making such issue.
We hope to see you more in the futue
