### ISSUE TITLE
[Feat]: Improve dropdown user experience

### ISSUE THREAD

**Issue by bulletinmybeard** [AliReza1083/AniLearn.dev#25]
### Description

Dropdown elements, such as for the `ratio` on the https://www.anilearn.dev/css/filter page, do not update on change and do not show the initial option. 

### Solution

Consider displaying the default option (e.g., `landscape` instead of `ratio`) and use `ratio` as label above or next to the dropdown. It makes it more clear to the user which option is active and to which option the dropdown was changed to.

<img width="596" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/e63455d1-e09a-40d8-a531-f311591c4279">

### Anything else?

This applies to all pages where dropdown elements are being used.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
This issue has been fixed.
Thanks for the issue

**Comment by bulletinmybeard** [comment]
Awesome, thx!!!
