### ISSUE TITLE
[Other]: Remove links for pages that will come soon (e.g., Flex Order)

### ISSUE THREAD

**Issue by bulletinmybeard** [AliReza1083/AniLearn.dev#26]
### Description

The current `Flex Order` demo page is coming soon but there is already a link to a page that does not exist yet.

<img width="517" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/3b0e89cf-83b2-487f-8ce9-249e8d7c2d40">

### Anything else?

Consider removing the link and use `opacity: 60%;` or a darker text color, etc. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
There is a page for flex-order now.
