### ISSUE TITLE
[Feat]: Improve UX on Open Graph demo page

### ISSUE THREAD

**Issue by bulletinmybeard** [AliReza1083/AniLearn.dev#27]
### Description

The placeholder URL input shows `https://` but the URL from the preview to the right starts with `www.`.
Based on the placeholder, I should use something like `https://rschu.me/` which will result into `WWW.HTTPS://RSCHU.ME/`.

<img width="971" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/9c7050e4-79ff-44b2-9cb5-04f2f9ba0336">

<img width="943" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/86a40eea-69fd-4dc9-88a9-1c3325d1625e">

### Solution

You might want to make it more clear which URL format is valid to avoid issues like that.

<img width="986" alt="image" src="https://github.com/AliReza1083/AniLearn.dev/assets/2648783/1038f5a3-1a52-4215-93c5-6eae58dc83a0">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
Thanks for creating issues about the website,
Are you willing to fix the issues, so that I can assign them to you?

**Comment by AliReza1083** [comment]
This issue has been fixed.
Thanks for the issues

**Comment by bulletinmybeard** [comment]
Has it tho? I still see the issues 😄

**Comment by AliReza1083** [comment]
I just changed the placeholder.
