### ISSUE TITLE
[Bug]: Github Button in CSS does not redirect to repository link

### ISSUE THREAD

**Issue by Ameya02** [AliReza1083/AniLearn.dev#28]
### Description

When I was at box model page of css and I tried to visit the repository by clicking on the github button it loaded the same page instead of github repo
I will solve this issue 

### To Reproduce

1. Go to 'https://www.anilearn.dev/css/'
2. Click on 'github icon button'
3. See error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
Hi @Ameya02 

This issue will be assigned to you.
Thanks for spotting the issue.

**Comment by AliReza1083** [comment]
Done ✅
