### ISSUE TITLE
[Other]: CSS: Opacity 

### ISSUE THREAD

**Issue by Ameya02** [AliReza1083/AniLearn.dev#30]
### Description

CSS opacity property that set transparency of an element
I want to add this into the project

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/AliReza1083/AniLearn.dev/blob/main/CODE_OF_CONDUCT.md)

**Comment by AliReza1083** [comment]
Sure, You can do it.

**Comment by Ameya02** [comment]
@AliReza1083 Template is not working. It giving me both error and successful message at the same time and not creating file

**Comment by AliReza1083** [comment]
Ohhh, You need to download it's package.

Simply go to the Templete folder and run `pnpm i` for installing the NPM packages.

**Comment by Ameya02** [comment]
I had already installed the packages
![image](https://github.com/AliReza1083/AniLearn.dev/assets/65841021/e5fb5c26-2be6-408e-94f5-987f7bdf0cca)

**Comment by AliReza1083** [comment]
Ok, let me check it

**Comment by AliReza1083** [comment]
![image](https://github.com/AliReza1083/AniLearn.dev/assets/99729607/71199334-c40c-4e29-bc0e-70651dc1f3fe)

The code was okay, the problem is: "it is finding the folder anilearn for creating the file."

`Solution: Change the name of folder to be anilearn.`

**Comment by AliReza1083** [comment]
I will fix the issue later.

**Comment by AliReza1083** [comment]
Is it working?

**Comment by AliReza1083** [comment]
The issue has been fixed.

**Comment by Ameya02** [comment]
Yes it is working now
