### ISSUE TITLE
[Feat]: Add JavaScript  Section

### ISSUE THREAD

**Issue by abbas-roholamin** [AliReza1083/AniLearn.dev#31]
What if we can add a JavaScript section as well @AliReza1083 ?

**Comment by AliReza1083** [comment]
That is a great idea, @abbas-roholamin.
Can you give some ideas for making a few pages?

Like for CSS, we have flex-position, position and more.
what about JavaScript?

**Comment by abbas-roholamin** [comment]
Yes, for example, we can create a page about how functions related to arrays work and show with animation how they work, what they return, and whether they change the information or not.
And maybe we can animate a little deeper topics that the others explain with the text

**Comment by AliReza1083** [comment]
Sure, I will think about it, currently I am busy with other things.
Once I start making the JS section, I will contact you to help with this.

**Comment by abbas-roholamin** [comment]
Ok sure
